import type { Metadata } from "next";
import "@repo/uikit/styles/index.css";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang="en"
			data-theme="light"
			data-brand="words-control"
			data-platform="desktop"
		>
			<body>{children}</body>
		</html>
	);
}
