export const DATA_SOURCE = "DATA_SOURCE";

export const USER_REPOSITORY = "USER_REPOSITORY";
export const LEARNING_REPOSITORY = "LEARNING_REPOSITORY";
export const TOPIC_REPOSITORY = "TOPIC_REPOSITORY";
export const TRAINING_REPOSITORY = "TRAINING_REPOSITORY";
export const VOCABCATALOG_REPOSITORY = "VOCABCATALOG_REPOSITORY";
export const WORD_REPOSITORY = "WORD_REPOSITORY";
export const WORDS_TRANSLATION_REPOSITORY = "WORDS_TRANSLATION_REPOSITORY";
export const REPORT_REPOSITORY = "REPORT_REPOSITORY";
