export const DATA_SOURCE = "DATA_SOURCE";

export const USER_REPOSITORY = "USER_REPOSITORY";
export const LEARNING_REPOSITORY = "LEARNING_REPOSITORY";
export const TOPIC_REPOSITORY = "TOPIC_REPOSITORY";
export const TRAINING_REPOSITORY = "TRAINING_REPOSITORY";
export const VOCABCATALOG_REPOSITORY = "VOCABCATALOG_REPOSITORY";
export const WORD_REPOSITORY = "WORD_REPOSITORY";
export const WORDS_TRANSLATION_REPOSITORY = "WORDS_TRANSLATION_REPOSITORY";
export const TOPIC_TRANSLATION_REPOSITORY = "TOPIC_TRANSLATION_REPOSITORY";
export const REPORT_REPOSITORY = "REPORT_REPOSITORY";
export const WORD_DUPLICATE_GROUP_REPOSITORY =
	"WORD_DUPLICATE_GROUP_REPOSITORY";
export const WORD_SYNONYM_GROUP_REPOSITORY = "WORD_SYNONYM_GROUP_REPOSITORY";
export const USER_VOCABULARY_REPOSITORY = "USER_VOCABULARY_REPOSITORY";
export const DIALOGUE_SESSION_REPOSITORY = "DIALOGUE_SESSION_REPOSITORY";
export const DIALOGUE_THREAD_REPOSITORY = "DIALOGUE_THREAD_REPOSITORY";
export const DIALOGUE_MESSAGE_REPOSITORY = "DIALOGUE_MESSAGE_REPOSITORY";
export const DIALOGUE_CORRECTION_REPOSITORY = "DIALOGUE_CORRECTION_REPOSITORY";
export const DIALOGUE_WORD_EVENT_REPOSITORY = "DIALOGUE_WORD_EVENT_REPOSITORY";
export const LANGUAGE_SKILL_PROFILE_REPOSITORY =
	"LANGUAGE_SKILL_PROFILE_REPOSITORY";
export const LLM_USAGE_REPOSITORY = "LLM_USAGE_REPOSITORY";
